PrograMemo-Groom/youtube-clone

.gitignore
src/api/api.js
src/api/endpoint.js
src/components/main/Main.js
src/config/config.js
src/service/VideoService.js

✨ youtube API 추가

---

src/components/header/Header.js
src/components/header/Header.module.css
src/hooks/useNavigation.js

Header 부분 작업 완료
@jdaily00 마이페이지 이동하는 부분 이제 div에 걸어서 이동하시면 됩니다.

Header 부분 작업 완료

---

src/components/shorts/shorts.js

🔧페이지 작업을 위해 [components] 안에 [shorts] 폴더 추가했습니다.

🔧components-shorts 폴더 추가

---

src/components/myPage/MyPage.css
src/components/myPage/MyPage.js

✨ 내 페이지: 임의 데이터로 배치 완료

---

src/components/detail/Detail.js
src/components/detail/creatorReserveTap/CreatorReserveTap.css
src/components/detail/creatorReserveTap/CreatorReserveTap.js
src/components/detail/shortsTap/ShortsTap.css
src/components/detail/shortsTap/ShortsTap.js
src/utils/formatViewerCount.js

지금은 더미데이터로 동작함
추후 < , > 스크롤 기능 추가 예정

💄 쇼츠 탭 화면 추가

---

src/App.js
src/components/detail/Detail.js
src/components/detail/creatorReserveTap/CreatorReserveTap.css
src/components/detail/relatedVideo/RelatedVideo.css
src/components/detail/relatedVideo/RelatedVideo.js
src/components/detail/shortsTap/ShortsTap.css
src/components/detail/shortsTap/ShortsTap.js

💄 쇼츠 탭, 관련 영상 탭

---

src/components/myPage/MyPage.css
src/components/myPage/MyPage.js

관련없는 주석 삭제하고 코드도 정리했습니다
미디어쿼리도 컨텐츠 종류별로 나눴던 거 사이즈 하나에서 해결해서 중복 코드 좀 줄였고..

✨ 내 페이지 반응형 ui로 변경

---

public/assets/icon/more_btn_black.svg
src/components/detail/Detail.css
src/components/detail/Detail.js
src/components/detail/creatorReserveTap/CreatorReserveTap.css
src/components/detail/creatorReserveTap/CreatorReserveTap.js
src/components/detail/mainVideo/MainVideo.css
src/components/detail/mainVideo/MainVideo.js
src/components/detail/shortsTap/ShortsTap.js

위와 같이 완료 
아직 더 해야할 것들
input 클릭 시 취소 작성
위 콘솔 오류는 iframe으로 가져온 비디오 자체에서 발생하는 문제라서 해결이 안될듯 
요인으로는 AdBlock 이 확장프로그램을 차단하면서 발생한다고 함

💄 메인 비디오, 비디오 설명란, 댓글창까지 하드코딩으로 구조 완료

---

src/components/detail/mainVideo/MainVideo.js
src/components/detail/relatedVideo/RelatedVideo.js
src/utils/formatTimeDifference.js
src/utils/formatViewerCount.js

✨ 동영상 상세 ui 간략하게 구현 완료 (더미데이터)

---

src/components/shorts/Panel.js
src/components/shorts/Panel.module.css
src/components/shorts/Shorts.module.css
src/components/shorts/Video.js
src/components/shorts/Video.module.css

💄 shorts 컴포넌트 별 레이아웃 및 스타일링

---

src/components/main/Main.js
src/components/main/category/CategoryBar.js
src/components/main/videos/MainVideos.js
src/components/sidebar/Sidebar.js

- 사이드바 버튼 클릭시 해당 페이지에 색상 변경되게 구현
<br><br>
- 카테고리별 버튼 클릭시 렌더링되게 코드 변경

💄 사이드바 버튼 클릭시 해당 페이지에 색상 변경되게 구현, 카테고리별 버튼 클릭시 렌더링되게 코드 변경

---

src/components/context/context.js
src/components/detail/Detail.css
src/components/detail/Detail.js
src/components/detail/creatorReserveTap/CreatorReserveTap.css
src/components/detail/creatorReserveTap/CreatorReserveTap.js
src/components/detail/mainVideo/MainVideo.css
src/components/detail/mainVideo/MainVideo.js
src/components/detail/relatedVideo/RelatedVideo.css
src/components/detail/relatedVideo/RelatedVideo.js
src/components/detail/shortsTap/ShortsTap.css
src/components/detail/shortsTap/ShortsTap.js
src/components/detail/themes/useThemeStyles.js

헤더사이드바는 제가 작업하는 곳이 아니라서.. 안건드렸습니다

💄 동영상 상세 페이지 다크모드 

---

src/components/myPage/MyPage.css
src/components/myPage/MyPage.js

✨ 마이페이지: 반응형 웹 수정, CSS 중복 코드 줄임

---

src/api/endpoint.js
src/components/myPage/MyPage.css

미안합니다... 화면 줄였을 때 다른 분들 화면까지 깨지는 거 해결했어요

💄 마이페이지 UI 변경

---

src/components/detail/Detail.css
src/components/detail/Detail.js
src/components/detail/creatorReserveTap/CreatorReserveTap.css
src/components/detail/mainVideo/MainVideo.js
src/utils/getChannelSubscriberCount.js

🎨 동영상 상세 페이지 api 데이터 적용 (메인 비디오, 설명탭, 댓글 갯수)

---

src/components/detail/creatorReserveTap/CreatorReserveTap.js
src/components/detail/mainVideo/MainVideo.css
src/components/detail/mainVideo/MainVideo.js
src/components/detail/relatedVideo/RelatedVideo.js
src/utils/fetchVideoComments.js

🎨 더미데이터 -> api 데이터 , 메인비디오와 댓글 창까지 완료 

---

src/api/endpoint.js
src/components/search/Search.js
src/components/search/Search.module.css
src/hooks/useIntersectionObserver.js
src/service/SearchService.js
src/service/VideoService.js

util에 피드 새로고침 하듯이 계속 불러오는 부분 생성은 해놨는데, 
회의때 설명 하도록 함

♻️ searchVideo API 리팩토링 및 ⚡️ 성능 개선

---

src/components/shorts/Panel.module.css
src/components/shorts/Video.js
src/components/shorts/Video.module.css

💄 Video UI 오류 수정

---

src/components/shorts/Panel.js
src/components/shorts/Panel.module.css
src/components/shorts/Video.js
src/components/shorts/comment/Comment.js
src/components/shorts/explain/Explain.js

댓글창 UI 대충 구현
컴포넌트로 내용 분리. 내용만 렌더링되도록 할 예정

🎨 Panel안 내용 컴포넌트로 분리

---

src/components/detail/Detail.js
src/components/detail/mainVideo/MainVideo.js
src/components/detail/shortsTap/ShortsTap.css
src/components/detail/shortsTap/ShortsTap.js
src/components/detail/shortsTap/fetchShortsVideos.js
src/service/VideoService.js
src/utils/fetchShortsVideos.js

🎨 더미데이터 ->api  데이터 (쇼츠 탭)

---

src/components/myPage/SortDropdown.css

💄 마이페이지: 드롭다운 백그라운드 컬러 수정

---

src/components/main/videos/MainVideos.js
src/components/main/videos/MainVideos.module.css
src/service/MainService.js

💄 메인 프로필 사진 클릭 시 프로필 페이지 이동

---

src/components/myPage/MyPage.css
src/components/myPage/MyPage.js
src/components/myPage/SortDropdown.css

api 할당량 다 쓴 김에.. pr하기...
짜잘한 것들 수정했어용

✨ 마이페이지: 기능 및 CSS 추가

---

src/components/search/Search.js
src/components/search/Search.module.css
src/service/SearchService.js

⚡️ 4차 API response : 중복 videoId 예외처리 진행
💄 이미지 해상도 떨어짐 issue로 수정
🎨 마우스 hover하면 영상 재생
💄 img style 추가
💡 오류 처리.. log찍는 부분 수정
✨ 무한 스크롤 기능 추가

✨ 무한 스크롤 기능 추가

---

src/components/detail/Detail.css
src/components/detail/Detail.js
src/components/detail/creatorReserveTap/CreatorReserveTap.css
src/components/detail/creatorReserveTap/CreatorReserveTap.js
src/components/detail/mainVideo/MainVideo.css
src/components/detail/mainVideo/MainVideo.js
src/components/detail/relatedVideo/RelatedVideo.css
src/components/detail/relatedVideo/RelatedVideo.js
src/components/detail/shortsTap/ShortsTap.css
src/components/detail/shortsTap/ShortsTap.js

1. 더보기 버튼 추가 및 동작하게 (보미님 코드 참고) 
2. 채널 프로필 이미지 클릭하면 채널페이지로 이동하게 (경희님 코드)
3. 영상 클릭 시 댓글 상태 변경
4. 썸네일 클릭 시 해당 영상 이동

🎨 디테일 페이지 dialog 추가

---

src/components/main/category/CategoryBar.js
src/components/main/videos/MainVideos.js
src/components/main/videos/MainVideos.module.css
src/service/MainService.js

- 메인 영상 프로필 연결 수정
- 섬네일 크기 일치하게 조정
- 오류나는 카테고리 삭제
- 무한스크롤 시도의 흔적.. -> 실패

💄 메인 영상 프로필 연결 수정, 섬네일 크기 일치하게 조정 

---

src/components/detail/mainVideo/MainVideo.css
src/components/detail/mainVideo/MainVideo.js

💄 mainVideo 더보기 모달 위치 수정

---

src/components/shorts/Video.js
src/components/shorts/comment/Comment.js
src/components/shorts/explain/Explain.js

🎨 short waring 제거

---

src/components/header/Header.js
src/components/subscribe/grid/Grid-subscribe.js
src/components/subscribe/grid/Grid-subscribe.module.css
src/components/subscribe/list/Listed-subscribe.js
src/components/subscribe/list/Listed-subscribe.module.css
src/components/subscribe/manage/Manage-subscribe.js
src/service/SubscribeService.js

- shorts 섹션 수정 (구현 완료)
- 인증토큰발급 구독->헤더로 수정 (구현완료)

✨인증토큰발급 헤더 버튼에서 가능하도록 수정

---

src/components/main/videos/MainVideos.js
src/components/main/videos/MainVideos.module.css
src/service/MainService.js

✨메인 영상 크기 동일하게, 무한 스크롤 기능 완료 

---

package-lock.json
package.json
src/components/detail/creatorReserveTap/CreatorReserveTap.css
src/components/detail/creatorReserveTap/CreatorReserveTap.js
src/components/detail/mainVideo/MainVideo.css
src/components/detail/mainVideo/MainVideo.js

댓글 내 링크 가능하게 
구독 상태 클릭 시 상태 변경
메뉴 탭들 hover 시 opacity 값 조정

💄메인 페이지 디자인 수정

---

package-lock.json
package.json
src/components/detail/Detail.js
src/components/detail/creatorReserveTap/CreatorReserveTap.js
src/components/detail/creatorReserveTap/videos/Videos.js
src/components/detail/mainVideo/comments/Comments.js
src/components/detail/relatedVideo/RelatedVideo.js
src/components/detail/shortsTap/ShortsTap.js
src/utils/fetchCreatorVideos.js

🎨 관련 동영상 탭 무한 스크롤 

---

src/components/detail/Detail.js

:art: 주석처리해뒀던 relatedVideos 컴포넌트 주석제거

---

src/components/subscribe/grid/Grid-subscribe.js
src/components/subscribe/grid/Grid-subscribe.module.css
src/components/subscribe/list/Listed-subscribe.js
src/components/subscribe/list/Listed-subscribe.module.css
src/service/SubscribeService.js

- 동영상, 숏츠 호버링 시 영상 재생 구현
- 미디어쿼리 깨진 부분 수정 완료
- border-radius등 깨진 css 수정 완료
- 동영상, 쇼츠 클릭시 채널페이지, 상세페이지로 이동 구현

✨그리드, 리스트 페이지 커서 포인터 추가
